import {Button,Input} from "../../components/ui";
import {blankMeeting,type CourseInput,type Meeting} from "./types";

export function CourseEditor({value,setValue,busy,error,onSave,onCancel}: {value:CourseInput;setValue:(v:CourseInput)=>void;busy:boolean;error:string;onSave:()=>void;onCancel:()=>void}){
 const patch=(p:Partial<CourseInput>)=>setValue({...value,...p}); const meeting=(i:number,p:Partial<Meeting>)=>patch({meetings:value.meetings.map((m,n)=>n===i?{...m,...p}:m)});
 return <form className="tt-editor" onSubmit={e=>{e.preventDefault();onSave()}}><fieldset disabled={busy}><h2>课程资料</h2>{error&&<p role="alert" className="error">{error}</p>}<div className="tt-form-grid"><label>课程号<Input value={value.code} onChange={e=>patch({code:e.target.value})}/></label><label>课程名<Input required value={value.title} onChange={e=>patch({title:e.target.value})}/></label><label>班级<Input value={value.class_name} onChange={e=>patch({class_name:e.target.value})}/></label><label>校区<Input value={value.campus} onChange={e=>patch({campus:e.target.value})}/></label></div>
 {value.meetings.map((m,i)=><fieldset className="tt-meeting" aria-label={`安排 ${i+1}`} key={i}><legend>安排 {i+1}</legend><div className="tt-form-grid"><label>星期<select value={m.day} onChange={e=>meeting(i,{day:+e.target.value})}>{[1,2,3,4,5,6,7].map(x=><option key={x} value={x}>周{"一二三四五六日"[x-1]}</option>)}</select></label><label>起始节<Input type="number" min="1" max="14" value={m.start_period} onChange={e=>meeting(i,{start_period:+e.target.value})}/></label><label>结束节<Input type="number" min="1" max="14" value={m.end_period} onChange={e=>meeting(i,{end_period:+e.target.value})}/></label><label>起始周<Input type="number" min="1" max="53" value={m.start_week} onChange={e=>meeting(i,{start_week:+e.target.value})}/></label><label>结束周<Input type="number" min="1" max="53" value={m.end_week} onChange={e=>meeting(i,{end_week:+e.target.value})}/></label><label>周次<select value={m.parity} onChange={e=>meeting(i,{parity:e.target.value as Meeting["parity"]})}><option value="all">每周</option><option value="odd">单周</option><option value="even">双周</option></select></label><label>教师<Input value={m.teacher} onChange={e=>meeting(i,{teacher:e.target.value})}/></label><label>地点<Input value={m.location} onChange={e=>meeting(i,{location:e.target.value})}/></label></div>{value.meetings.length>1&&<Button type="button" variant="ghost" onClick={()=>patch({meetings:value.meetings.filter((_,n)=>n!==i)})}>删除安排</Button>}</fieldset>)}
 <div className="tt-actions"><Button type="button" variant="outline" onClick={()=>patch({meetings:[...value.meetings,blankMeeting()]})}>添加安排</Button><Button type="submit" disabled={!value.title.trim()}>保存课程</Button><Button type="button" variant="ghost" onClick={onCancel}>取消</Button></div></fieldset></form>;
}
