import{useEffect,useMemo,useRef,useState}from"react";import{api}from"../../api";import{Button,Confirm,Input,type Confirmation}from"../../components/ui";import{maxBrowsableWeek,teachingWeek}from"./calendar";import{CourseEditor}from"./CourseEditor";import{ImportPanel}from"./ImportPanel";import{blankCourse,type Course,type CourseInput,type Settings}from"./types";import{WeekGrid}from"./WeekGrid";import"./timetable.css";
export function TimetablePanel({active,onDraftChange}:{active:boolean;onDraftChange:(dirty:boolean)=>void}){const[courses,setCourses]=useState<Course[]>([]),[settings,setSettings]=useState<Settings>({week_one_monday:null,total_weeks:20,version:0}),[loaded,setLoaded]=useState(false),[week,setWeek]=useState(1),[mode,setMode]=useState<"none"|"edit"|"import"|"settings">("none"),[draft,setDraft]=useState<CourseInput|null>(null),[editing,setEditing]=useState<Course|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[confirm,setConfirm]=useState<Confirmation|null>(null),[settingsDraft,setSettingsDraft]=useState<Settings|null>(null),selectedWeek=useRef(false);const guarded=mode!=="none"||busy;
 async function load(){setBusy(true);setError("");try{const[c,s]=await Promise.all([api<Course[]>("/timetable/courses"),api<Settings>("/timetable/settings")]);setCourses(c);setSettings(s);if(!selectedWeek.current)setWeek(teachingWeek(s.week_one_monday,s.total_weeks,new Date())?.week??1);setLoaded(true)}catch(e){setError(e instanceof Error?e.message:"加载失败")}finally{setBusy(false)}}
 useEffect(()=>{if(active&&!loaded)void load()},[active,loaded]);
 useEffect(()=>{onDraftChange(guarded);return()=>onDraftChange(false)},[guarded,onDraftChange]);useEffect(()=>{const h=(e:BeforeUnloadEvent)=>{if(guarded){e.preventDefault();e.returnValue=""}};window.addEventListener("beforeunload",h);return()=>window.removeEventListener("beforeunload",h)},[guarded]);
 const maximum=maxBrowsableWeek(settings.total_weeks,courses),today=teachingWeek(settings.week_one_monday,settings.total_weeks,new Date());
 function openCourse(c?:Course){setEditing(c??null);setDraft(c?structuredClone(c):blankCourse());setError("");setMode("edit")}
 function cancel(){const close=()=>{setMode("none");setDraft(null);setSettingsDraft(null);setError("")};if(mode!=="none")setConfirm({title:"放弃当前草稿？",description:"尚未保存的内容会丢失。",label:"放弃修改",action:close});else close()}
 async function saveCourse(){if(!draft)return;setBusy(true);setError("");try{const saved=editing?await api<Course>(`/timetable/courses/${editing.id}`,"PUT",{...draft,version:editing.version}):await api<Course>("/timetable/courses","POST",draft);setCourses(cs=>editing?cs.map(c=>c.id===saved.id?saved:c):[...cs,saved]);setMode("none");setDraft(null);setNotice("课程已保存。")}catch(e){setError(e instanceof Error?e.message:"保存失败")}finally{setBusy(false)}}
 async function remove(c:Course){setConfirm({title:`删除“${c.title}”？`,description:"课程及全部安排会被删除。",label:"删除课程",action:async()=>{setBusy(true);try{await api(`/timetable/courses/${c.id}`,"DELETE");setCourses(cs=>cs.filter(x=>x.id!==c.id));setNotice("课程已删除。")}catch(e){setError(e instanceof Error?e.message:"删除失败")}finally{setBusy(false)}}})}
 async function saveSettings(){if(!settingsDraft)return;setBusy(true);setError("");try{const saved=await api<Settings>("/timetable/settings","PUT",settingsDraft);setSettings(saved);setSettingsDraft(null);setMode("none");setWeek(w=>Math.min(w,maxBrowsableWeek(saved.total_weeks,courses)));setNotice("学期设置已保存。")}catch(e){setError(e instanceof Error?e.message:"保存失败")}finally{setBusy(false)}}
 return <section className="timetable"><header className="tt-hero"><div className="tt-hero-copy"><span className="tt-theme-label"><span aria-hidden="true">✦</span> 炎之意志 · FLAME</span><h1>我的课表<span aria-hidden="true">.</span></h1><p>让热爱，成为每一天的动力。</p><div className="tt-hero-meta"><span>WEEK {String(week).padStart(2,"0")}</span><span>按周查看 · 共 {courses.length} 门课程</span></div></div></header><div className="tt-toolbar"><div><span className="eyebrow">YOUR WEEK, YOUR PACE</span><h2>本周安排</h2></div><Button disabled={guarded} onClick={()=>openCourse()}><span aria-hidden="true">＋</span> 添加课程</Button><Button variant="outline" disabled={guarded} onClick={()=>setMode("import")}>粘贴导入</Button><Button variant="ghost" disabled={guarded} onClick={()=>{setSettingsDraft({...settings});setMode("settings")}}>学期设置</Button></div>{error&&mode==="none"&&<p role="alert" className="error">{error}<Button variant="ghost" disabled={busy} onClick={()=>void load()}>重试</Button></p>}{notice&&<p role="status">{notice}</p>}
 <div className="tt-weekbar"><Button variant="ghost" disabled={week<=1} onClick={()=>setWeek(w=>w-1)}>上一周</Button><label>教学周<select value={week} onChange={e=>{selectedWeek.current=true;setWeek(+e.target.value)}}>{Array.from({length:maximum},(_,i)=><option value={i+1} key={i}>第 {i+1} 周</option>)}</select></label><Button variant="ghost" disabled={week>=maximum} onClick={()=>setWeek(w=>w+1)}>下一周</Button><Button variant="outline" disabled={!today} onClick={()=>today&&setWeek(today.week)}>当前周</Button><span>{!settings.week_one_monday?"尚未设置第一周周一日期":today?.position==="before"?"当前日期在学期开始前":today?.position==="after"?"当前日期在学期结束后":`当前为第 ${today?.week} 周`}</span></div>
 <WeekGrid courses={courses} week={week} onOpenCourse={openCourse} disabled={guarded}/><details className="tt-library"><summary>全部课程 <span>{courses.length} 门 · 展开管理</span></summary>{courses.map(c=><article key={c.id}><div><strong>{c.title}</strong><span>{c.code} · {c.class_name} · {c.campus} · {c.meetings.length} 条安排</span></div><Button variant="ghost" aria-label={`编辑 ${c.title}`} onClick={()=>openCourse(c)}>编辑</Button><Button variant="danger" onClick={()=>void remove(c)}>删除</Button></article>)}</details>{loaded&&!courses.length&&<p>还没有课程，可以手动添加或粘贴课程表导入。</p>}
 {mode==="edit"&&draft&&<CourseEditor value={draft} setValue={setDraft} busy={busy} error={error} onSave={()=>void saveCourse()} onCancel={cancel}/>} {mode==="import"&&<div className="tt-editor"><div className="tt-actions"><h2>粘贴导入</h2><Button variant="ghost" onClick={cancel}>取消</Button></div><ImportPanel onBusy={setBusy} onDone={(created,message)=>{setCourses(c=>[...c,...created]);setNotice(message);setMode("none")}}/></div>}
 {mode==="settings"&&settingsDraft&&<form className="tt-editor" onSubmit={e=>{e.preventDefault();void saveSettings()}}><h2>学期设置</h2>{error&&<p role="alert">{error}</p>}<div className="tt-form-grid"><label>第一周周一<Input aria-label="第一周周一" type="date" value={settingsDraft.week_one_monday??""} onChange={e=>setSettingsDraft({...settingsDraft,week_one_monday:e.target.value||null})}/></label><label>总周数<Input aria-label="总周数" type="number" min="1" max="53" value={settingsDraft.total_weeks} onChange={e=>setSettingsDraft({...settingsDraft,total_weeks:+e.target.value})}/></label></div><div className="tt-actions"><Button type="submit">保存设置</Button><Button type="button" variant="ghost" onClick={cancel}>取消</Button></div></form>}<Confirm value={confirm} onClose={()=>setConfirm(null)}/></section>}

